spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          log-slow-sql: true    #慢SQL日志
          slow-sql-millis: 1000
          merge-sql: true
          wall:
            config:
              multi-statement-allow: true
            commons-log:
              statement-log-enabled: true
              statement-executable-sql-log-enable: true
            initialSize: 5
            maxActive: 20
            maxPoolPreparedStatementPerConnectionSize: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 5
            poolPreparedStatements: true
            testOnBorrow: false
            testOnReturn: false
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            validationQuery: SELECT 1 FROM DUAL
      url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: liwenbin21